[package]
org = "nilukadevspecialusecases"
name = "asgardeo_e2e_special_cases"
version = "1.0.0"
distribution = "2201.8.8"

[build-options]
observabilityIncluded = true
cloud = "choreo"

# Choreo-specific metadata
[package.metadata]
description = "Asgardeo E2E Special Cases - JWT Authentication Extension API"
keywords = ["authentication", "jwt", "asgardeo", "e2e", "special-cases", "webhook"]
repository = "https://github.com/NilukaSripalim/action.git"
license = "MIT"
